version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    rebase-strategy: auto
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    labels:
      - dependencies
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
      typescript:
        patterns:
          - typescript
          - '@types/*'
        exclude-patterns:
          - '@types/eslint'
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
          - 'netlify-*'
          - 'astro-*'
      eslint:
        patterns:
          - '*eslint*'
      css:
        patterns:
          - 'tailwindcss'
          - 'postcss'
