module.exports = {
  docs: [
    // {
    //   type: "category",
    //   label: "Protips",
    //   link: {
    //     type: "generated-index",
    //     title: "Protips",
    //     slug: "protips/index",
    //   },
    //   items: [{ type: "autogenerated", dirName: "protips" }],
    // },
    "about",
    "resume",
  ],
};
